

# 
# mts_preprocessor "MuTRiG Timestamp Processor" v2.0.17
# Yifeng Wang 2024.08.09.15:26:09
# Decode the hits from MuTRiG 
# 
# 25.0.0306 - add <debug_burst> interface 
# 25.0.0924 - supports e-flag from mutrig, to indicate if ecc is valid

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mts_preprocessor
# 
set_module_property DESCRIPTION "Decode the hits from MuTRiG "
set_module_property NAME mts_preprocessor
set_module_property VERSION 25.0.0924
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Mu3e Data Plane/Modules"
set_module_property AUTHOR "Yifeng Wang"
set_module_property DISPLAY_NAME "MuTRiG Timestamp Processor"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mts_processor
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file mts_processor.vhd VHDL PATH mts_processor.vhd TOP_LEVEL_FILE
add_fileset_file dual_port_rom.v VERILOG PATH dual_port_rom.v
add_fileset_file dual_port_rom_init.txt OTHER PATH dual_port_rom_init.txt


# 
# parameters
# 
add_parameter FRAME_CORRPT_BIT_LOC NATURAL 2
set_parameter_property FRAME_CORRPT_BIT_LOC DEFAULT_VALUE 2
set_parameter_property FRAME_CORRPT_BIT_LOC DISPLAY_NAME FRAME_CORRPT_BIT_LOC
set_parameter_property FRAME_CORRPT_BIT_LOC TYPE NATURAL
set_parameter_property FRAME_CORRPT_BIT_LOC ENABLED false
set_parameter_property FRAME_CORRPT_BIT_LOC UNITS None
set_parameter_property FRAME_CORRPT_BIT_LOC ALLOWED_RANGES 0:2147483647
set_parameter_property FRAME_CORRPT_BIT_LOC HDL_PARAMETER true
add_parameter CRCERR_BIT_LOC NATURAL 1
set_parameter_property CRCERR_BIT_LOC DEFAULT_VALUE 1
set_parameter_property CRCERR_BIT_LOC DISPLAY_NAME CRCERR_BIT_LOC
set_parameter_property CRCERR_BIT_LOC TYPE NATURAL
set_parameter_property CRCERR_BIT_LOC ENABLED false
set_parameter_property CRCERR_BIT_LOC UNITS None
set_parameter_property CRCERR_BIT_LOC ALLOWED_RANGES 0:2147483647
set_parameter_property CRCERR_BIT_LOC HDL_PARAMETER true
add_parameter HITERR_BIT_LOC NATURAL 0
set_parameter_property HITERR_BIT_LOC DEFAULT_VALUE 0
set_parameter_property HITERR_BIT_LOC DISPLAY_NAME HITERR_BIT_LOC
set_parameter_property HITERR_BIT_LOC TYPE NATURAL
set_parameter_property HITERR_BIT_LOC ENABLED false
set_parameter_property HITERR_BIT_LOC UNITS None
set_parameter_property HITERR_BIT_LOC ALLOWED_RANGES 0:2147483647
set_parameter_property HITERR_BIT_LOC HDL_PARAMETER true
add_parameter BANK STRING UP
set_parameter_property BANK DEFAULT_VALUE UP
set_parameter_property BANK DISPLAY_NAME BANK
set_parameter_property BANK TYPE STRING
set_parameter_property BANK UNITS None
set_parameter_property BANK HDL_PARAMETER true
add_parameter ENABLED_CHANNEL_HI NATURAL 3
set_parameter_property ENABLED_CHANNEL_HI DEFAULT_VALUE 3
set_parameter_property ENABLED_CHANNEL_HI DISPLAY_NAME ENABLED_CHANNEL_HI
set_parameter_property ENABLED_CHANNEL_HI TYPE NATURAL
set_parameter_property ENABLED_CHANNEL_HI UNITS None
set_parameter_property ENABLED_CHANNEL_HI ALLOWED_RANGES 0:2147483647
set_parameter_property ENABLED_CHANNEL_HI HDL_PARAMETER true
add_parameter ENABLED_CHANNEL_LO NATURAL 0
set_parameter_property ENABLED_CHANNEL_LO DEFAULT_VALUE 0
set_parameter_property ENABLED_CHANNEL_LO DISPLAY_NAME ENABLED_CHANNEL_LO
set_parameter_property ENABLED_CHANNEL_LO TYPE NATURAL
set_parameter_property ENABLED_CHANNEL_LO UNITS None
set_parameter_property ENABLED_CHANNEL_LO ALLOWED_RANGES 0:2147483647
set_parameter_property ENABLED_CHANNEL_LO HDL_PARAMETER true
add_parameter PADDING_EOP_WAIT_CYCLE NATURAL 512
set_parameter_property PADDING_EOP_WAIT_CYCLE DEFAULT_VALUE 512
set_parameter_property PADDING_EOP_WAIT_CYCLE DISPLAY_NAME PADDING_EOP_WAIT_CYCLE
set_parameter_property PADDING_EOP_WAIT_CYCLE TYPE NATURAL
set_parameter_property PADDING_EOP_WAIT_CYCLE UNITS None
set_parameter_property PADDING_EOP_WAIT_CYCLE ALLOWED_RANGES 0:2147483647
set_parameter_property PADDING_EOP_WAIT_CYCLE HDL_PARAMETER true
add_parameter LPM_DIV_PIPELINE NATURAL 2
set_parameter_property LPM_DIV_PIPELINE DEFAULT_VALUE 2
set_parameter_property LPM_DIV_PIPELINE DISPLAY_NAME LPM_DIV_PIPELINE
set_parameter_property LPM_DIV_PIPELINE TYPE NATURAL
set_parameter_property LPM_DIV_PIPELINE UNITS None
set_parameter_property LPM_DIV_PIPELINE ALLOWED_RANGES 0:2147483647
set_parameter_property LPM_DIV_PIPELINE HDL_PARAMETER true
add_parameter MUTRIG_BUFFER_EXPECTED_LATENCY_8N NATURAL 2000
set_parameter_property MUTRIG_BUFFER_EXPECTED_LATENCY_8N DEFAULT_VALUE 2000
set_parameter_property MUTRIG_BUFFER_EXPECTED_LATENCY_8N DISPLAY_NAME MUTRIG_BUFFER_EXPECTED_LATENCY_8N
set_parameter_property MUTRIG_BUFFER_EXPECTED_LATENCY_8N TYPE NATURAL
set_parameter_property MUTRIG_BUFFER_EXPECTED_LATENCY_8N UNITS None
set_parameter_property MUTRIG_BUFFER_EXPECTED_LATENCY_8N ALLOWED_RANGES 0:2147483647
set_parameter_property MUTRIG_BUFFER_EXPECTED_LATENCY_8N HDL_PARAMETER true
add_parameter DEBUG NATURAL 1
set_parameter_property DEBUG DEFAULT_VALUE 1
set_parameter_property DEBUG DISPLAY_NAME DEBUG
set_parameter_property DEBUG TYPE NATURAL
set_parameter_property DEBUG ENABLED false
set_parameter_property DEBUG UNITS None
set_parameter_property DEBUG ALLOWED_RANGES 0:2147483647
set_parameter_property DEBUG HDL_PARAMETER true


# 
# display items
# 


# 
# connection point csr
# 
add_interface csr avalon end
set_interface_property csr addressUnits WORDS
set_interface_property csr associatedClock clock_interface
set_interface_property csr associatedReset reset_interface
set_interface_property csr bitsPerSymbol 8
set_interface_property csr burstOnBurstBoundariesOnly false
set_interface_property csr burstcountUnits WORDS
set_interface_property csr explicitAddressSpan 0
set_interface_property csr holdTime 0
set_interface_property csr linewrapBursts false
set_interface_property csr maximumPendingReadTransactions 0
set_interface_property csr maximumPendingWriteTransactions 0
set_interface_property csr readLatency 0
set_interface_property csr readWaitTime 1
set_interface_property csr setupTime 0
set_interface_property csr timingUnits Cycles
set_interface_property csr writeWaitTime 0
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr avs_csr_readdata readdata Output 32
add_interface_port csr avs_csr_read read Input 1
add_interface_port csr avs_csr_address address Input 3
add_interface_port csr avs_csr_waitrequest waitrequest Output 1
add_interface_port csr avs_csr_write write Input 1
add_interface_port csr avs_csr_writedata writedata Input 32
set_interface_assignment csr embeddedsw.configuration.isFlash 0
set_interface_assignment csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_interface
# 
add_interface clock_interface clock end
set_interface_property clock_interface clockRate 0
set_interface_property clock_interface ENABLED true
set_interface_property clock_interface EXPORT_OF ""
set_interface_property clock_interface PORT_NAME_MAP ""
set_interface_property clock_interface CMSIS_SVD_VARIABLES ""
set_interface_property clock_interface SVD_ADDRESS_GROUP ""

add_interface_port clock_interface i_clk clk Input 1


# 
# connection point reset_interface
# 
add_interface reset_interface reset end
set_interface_property reset_interface associatedClock clock_interface
set_interface_property reset_interface synchronousEdges DEASSERT
set_interface_property reset_interface ENABLED true
set_interface_property reset_interface EXPORT_OF ""
set_interface_property reset_interface PORT_NAME_MAP ""
set_interface_property reset_interface CMSIS_SVD_VARIABLES ""
set_interface_property reset_interface SVD_ADDRESS_GROUP ""

add_interface_port reset_interface i_rst reset Input 1


# 
# connection point run_ctrl
# 
add_interface run_ctrl avalon_streaming end
set_interface_property run_ctrl associatedClock clock_interface
set_interface_property run_ctrl associatedReset reset_interface
set_interface_property run_ctrl dataBitsPerSymbol 9
set_interface_property run_ctrl errorDescriptor ""
set_interface_property run_ctrl firstSymbolInHighOrderBits true
set_interface_property run_ctrl maxChannel 0
set_interface_property run_ctrl readyLatency 0
set_interface_property run_ctrl ENABLED true
set_interface_property run_ctrl EXPORT_OF ""
set_interface_property run_ctrl PORT_NAME_MAP ""
set_interface_property run_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property run_ctrl SVD_ADDRESS_GROUP ""

add_interface_port run_ctrl asi_ctrl_data data Input 9
add_interface_port run_ctrl asi_ctrl_valid valid Input 1
add_interface_port run_ctrl asi_ctrl_ready ready Output 1


# 
# connection point hit_type0_in
# 
add_interface hit_type0_in avalon_streaming end
set_interface_property hit_type0_in associatedClock clock_interface
set_interface_property hit_type0_in associatedReset reset_interface
set_interface_property hit_type0_in dataBitsPerSymbol 45
set_interface_property hit_type0_in errorDescriptor ""
set_interface_property hit_type0_in firstSymbolInHighOrderBits true
set_interface_property hit_type0_in maxChannel 63
set_interface_property hit_type0_in readyLatency 0
set_interface_property hit_type0_in ENABLED true
set_interface_property hit_type0_in EXPORT_OF ""
set_interface_property hit_type0_in PORT_NAME_MAP ""
set_interface_property hit_type0_in CMSIS_SVD_VARIABLES ""
set_interface_property hit_type0_in SVD_ADDRESS_GROUP ""

add_interface_port hit_type0_in asi_hit_type0_channel channel Input 6
add_interface_port hit_type0_in asi_hit_type0_startofpacket startofpacket Input 1
add_interface_port hit_type0_in asi_hit_type0_endofpacket endofpacket Input 1
add_interface_port hit_type0_in asi_hit_type0_error error Input 3
add_interface_port hit_type0_in asi_hit_type0_data data Input 45
add_interface_port hit_type0_in asi_hit_type0_valid valid Input 1
add_interface_port hit_type0_in asi_hit_type0_ready ready Output 1


# 
# connection point hit_type1_out
# 
add_interface hit_type1_out avalon_streaming start
set_interface_property hit_type1_out associatedClock clock_interface
set_interface_property hit_type1_out associatedReset reset_interface
set_interface_property hit_type1_out dataBitsPerSymbol 39
set_interface_property hit_type1_out errorDescriptor {"tserr"}
set_interface_property hit_type1_out firstSymbolInHighOrderBits true
set_interface_property hit_type1_out maxChannel 15
set_interface_property hit_type1_out readyLatency 0
set_interface_property hit_type1_out ENABLED true
set_interface_property hit_type1_out EXPORT_OF ""
set_interface_property hit_type1_out PORT_NAME_MAP ""
set_interface_property hit_type1_out CMSIS_SVD_VARIABLES ""
set_interface_property hit_type1_out SVD_ADDRESS_GROUP ""

add_interface_port hit_type1_out aso_hit_type1_data data Output 39
add_interface_port hit_type1_out aso_hit_type1_valid valid Output 1
add_interface_port hit_type1_out aso_hit_type1_ready ready Input 1
add_interface_port hit_type1_out aso_hit_type1_channel channel Output 4
add_interface_port hit_type1_out aso_hit_type1_endofpacket endofpacket Output 1
add_interface_port hit_type1_out aso_hit_type1_startofpacket startofpacket Output 1
add_interface_port hit_type1_out aso_hit_type1_empty empty Output 1
add_interface_port hit_type1_out aso_hit_type1_error error Output 1


# 
# connection point debug_ts
# 
add_interface debug_ts avalon_streaming start
set_interface_property debug_ts associatedClock clock_interface
set_interface_property debug_ts associatedReset reset_interface
set_interface_property debug_ts dataBitsPerSymbol 16
set_interface_property debug_ts errorDescriptor ""
set_interface_property debug_ts firstSymbolInHighOrderBits true
set_interface_property debug_ts maxChannel 0
set_interface_property debug_ts readyLatency 0
set_interface_property debug_ts ENABLED true
set_interface_property debug_ts EXPORT_OF ""
set_interface_property debug_ts PORT_NAME_MAP ""
set_interface_property debug_ts CMSIS_SVD_VARIABLES ""
set_interface_property debug_ts SVD_ADDRESS_GROUP ""

add_interface_port debug_ts aso_debug_ts_valid valid Output 1
add_interface_port debug_ts aso_debug_ts_data data Output 16


# 
# connection point debug_burst
# 
add_interface debug_burst avalon_streaming start
set_interface_property debug_burst associatedClock clock_interface
set_interface_property debug_burst associatedReset reset_interface
set_interface_property debug_burst dataBitsPerSymbol 16
set_interface_property debug_burst errorDescriptor ""
set_interface_property debug_burst firstSymbolInHighOrderBits true
set_interface_property debug_burst ENABLED true

add_interface_port debug_burst aso_debug_burst_valid valid Output 1
add_interface_port debug_burst aso_debug_burst_data data Output 16

